### ISSUE TITLE
Stop

### ISSUE THREAD

**Issue by Scuph** [IslandFreedom/AlexUtilsMod#1]
@AlexFreedomMod

Stop giving yourself all the credit in releases, commits and issues. You aren't even the lead or assistant lead dev, you are a regular one, you didn't get 'everything' working. You messed it up and we fixed it.

If you do it again, I will suspend you from the development team for 5 days.

**Comment by Scuph** [comment]
@IslandFreedom/owners This was meant for IFM. Not AUM

**Comment by AlexFreedomMod** [comment]
I coed that release by my self :/

**Comment by AlexFreedomMod** [comment]
And it's my plugin

**Comment by AlexFreedomMod** [comment]
Where is the file is it In the netbeans or eclipse brach branch

**Comment by AlexFreedomMod** [comment]
I gave everyone credit. I don't know where you saw where I didn't .

**Comment by tylerhyperHD** [comment]
I am going to end up fixing the plugin like a ton to make it actually work b/c its broke ATM. If we are missing credit, then commit and add the credit. Its not that hard, and you do not need to fight about it when you can simply commit fix it.
