### ISSUE TITLE
commit pom.xml

### ISSUE THREAD

**Issue by tylerhyperHD** [IslandFreedom/AlexUtilsMod#2]
Alex, if you are using eclipse, please commit the pom.XML so I can actually compile the project.

**Comment by AlexFreedomMod** [comment]
pom.XML?

**Comment by AlexFreedomMod** [comment]
Where do i get that from?

**Comment by tylerhyperHD** [comment]
The source folder/source code. It is an essential file that allows Eclipse
to commit/build.

**Comment by AlexFreedomMod** [comment]
you mean the src folder?

**Comment by AlexFreedomMod** [comment]
;/ stupid button

**Comment by AlexFreedomMod** [comment]
@tylerhyperHD i could not find it.

**Comment by tylerhyperHD** [comment]
pom.XML is what maven compiling uses. I highly recommend to convert it over to a maven plugin.

**Comment by AlexFreedomMod** [comment]
Some of the plugin is maven. we need to update all the branches to look like the eclipse one.

**Comment by AlexFreedomMod** [comment]
Well not exactly the same but a bit diffent. like all of the them have the same thing just compiled diffently.

**Comment by AlexFreedomMod** [comment]
Eclipse branch removed.
