### ISSUE TITLE
AlexUtilsMod cannot be resolved to a variable & type

### ISSUE THREAD

**Issue by AlexFreedomMod** [IslandFreedom/AlexUtilsMod#3]
07.05 21:39:21 [Server] ERROR Could not load 'plugins/AlexUtilsMod (2).jar' in folder 'plugins'
07.05 21:39:21 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problems: 
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO Syntax error on token "fianl", final expected
07.05 21:39:21 [Server] INFO fianl cannot be resolved to a type
07.05 21:39:21 [Server] INFO Syntax error on token "ChatColor", delete this token
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:258) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO Caused by: java.lang.Error: Unresolved compilation problems: 
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO Syntax error on token "fianl", final expected
07.05 21:39:21 [Server] INFO fianl cannot be resolved to a type
07.05 21:39:21 [Server] INFO Syntax error on token "ChatColor", delete this token
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a variable
07.05 21:39:21 [Server] INFO AlexUtilsMod cannot be resolved to a type
07.05 21:39:21 [Server] INFO at me.alex33856.alexutils.Utils.<init>(Utils.java:17) ~[?:?]
07.05 21:39:21 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45]
07.05 21:39:21 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45]
07.05 21:39:21 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45]
07.05 21:39:21 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
07.05 21:39:21 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_45]
07.05 21:39:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
07.05 21:39:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]

**Comment by AlexFreedomMod** [comment]
Should be fixed in the next release today.

**Comment by AlexFreedomMod** [comment]
Some issues have been fixed others are still being worked on

**Comment by tylerhyperHD** [comment]
Leave it to me to fix the eclipse version.

**Comment by AlexFreedomMod** [comment]
ok

**Comment by AlexFreedomMod** [comment]
Eclipse has been removed making this issue use less.
